#ifndef MONIKA_PROVIDER
#define MONIKA_PROVIDER(index)
#endif

// Currently, I cannot find a use case for running more than 16 different types of kernel ABI at
// the same time.

MONIKA_PROVIDER(0)
MONIKA_PROVIDER(1)
MONIKA_PROVIDER(2)
MONIKA_PROVIDER(3)
MONIKA_PROVIDER(4)
MONIKA_PROVIDER(5)
MONIKA_PROVIDER(6)
MONIKA_PROVIDER(7)
MONIKA_PROVIDER(8)
MONIKA_PROVIDER(9)
MONIKA_PROVIDER(10)
MONIKA_PROVIDER(11)
MONIKA_PROVIDER(12)
MONIKA_PROVIDER(13)
MONIKA_PROVIDER(14)
MONIKA_PROVIDER(15)
