function(git_run out_var command)
    separate_arguments(cmd_list NATIVE_COMMAND "${command}")
    execute_process(
        COMMAND git ${cmd_list}
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE result
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

git_run(CURRENT_BRANCH "branch --show-current")

if(CURRENT_BRANCH STREQUAL "master")
    git_run(MONIKA_BUILD_NUMBER "rev-list --count master")
else()
    git_run(MERGE_BASE "merge-base refs/remotes/origin/master HEAD")
    git_run(MASTER_COUNT "rev-list --count ${MERGE_BASE}")
    git_run(DIVERGE_COUNT "rev-list --count ${MERGE_BASE}..HEAD")

    set(MONIKA_BUILD_NUMBER "${MASTER_COUNT}+${DIVERGE_COUNT}")
endif()

# Git Properties
git_run(MONIKA_BUILD_TAG       "describe --broken --dirty --all")
git_run(MONIKA_BUILD_HASH      "rev-parse --short HEAD")
git_run(MONIKA_BUILD_HASH_FULL "rev-parse HEAD")
git_run(MONIKA_BUILD_ORIGIN    "remote get-url origin")

# Timestamp Properties
string(TIMESTAMP MONIKA_TIMESTAMP  "%a %b %d %H:%M:%S UTC %Y" UTC)
string(TIMESTAMP MONIKA_BUILD_YEAR "%Y")

# Author Properties
if(NOT MONIKA_BUILD_AUTHOR)
    set(MONIKA_BUILD_AUTHOR "Trung Nguyen")
endif()
if(MONIKA_BUILD_YEAR STREQUAL "2023")
    set(MONIKA_BUILD_COPYRIGHT_YEARS "2023")
else()
    set(MONIKA_BUILD_COPYRIGHT_YEARS "2023-${MONIKA_BUILD_YEAR}")
endif()

# Driver Name Properties
if(NOT MONIKA_BUILD_NAME)
    set(MONIKA_BUILD_NAME "lxmonika")
endif()

# Version Properties
if(NOT MONIKA_BUILD_VERSION)
    set(MONIKA_BUILD_VERSION "0.0.1.${MONIKA_BUILD_NUMBER}")
endif()

set(MONIKA_BUILD_PROPS
    BUILD_NUMBER
    BUILD_TAG
    BUILD_HASH
    BUILD_HASH_FULL
    BUILD_ORIGIN
    BUILD_YEAR
    BUILD_AUTHOR
    BUILD_COPYRIGHT_YEARS
    BUILD_NAME
    BUILD_VERSION
)

foreach(prop ${MONIKA_BUILD_PROPS})
    string(APPEND CONTENT_UNQUOTED
        "#define MONIKA_${prop} ${MONIKA_${prop}}\n"
    )
    string(APPEND CONTENT_QUOTED_ALTERNATIVE
        "#define MONIKA_QUOTED_${prop} \"${MONIKA_${prop}}\"\n"
    )
    string(APPEND CONTENT_QUOTED
        "#define MONIKA_${prop} \"${MONIKA_${prop}}\"\n"
    )
endforeach()

# Header Content
set(CONTENT "/* Auto-generated by CMake - do not edit */
#pragma once

#ifdef RC_INVOKED
// Do not quote properties for RC, they will be stringified later.
#define MONIKA_UNQUOTED_BUILD_PROPS
#endif

#ifdef MONIKA_UNQUOTED_BUILD_PROPS

${CONTENT_UNQUOTED}
${CONTENT_QUOTED_ALTERNATIVE}
#else

${CONTENT_QUOTED}
#undef MONIKA_UNQUOTED_BUILD_PROPS

#endif /* MONIKA_UNQUOTED_BUILD_PROPS */
")

# Only write if content changed.
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" OLD_CONTENT)
endif()

if(NOT "${CONTENT}" STREQUAL "${OLD_CONTENT}")
    file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
endif()
