//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by monika.rc
//
#define MA_STRING_EXCEPTION_COMMAND_NAME_CONFLICT 101
#define MA_STRING_EXCEPTION_INVALID_DRIVER_PATH 102
#define MA_STRING_EXCEPTION_VALUE_EXPECTED 103
#define MA_STRING_COMMAND_HELP_USAGE    104
#define MA_STRING_COMMAND_HELP_ARGUMENTS 105
#define MA_STRING_COMMAND_HELP_COMMANDS 106
#define MA_STRING_COMMAND_HELP_OPTIONS  107
#define MA_STRING_COMMAND_HELP_PLACEHOLDER_COMMAND 108
#define MA_STRING_COMMAND_HELP_PLACEHOLDER_OPTIONS 109
#define MA_STRING_COMMAND_HELP_COPYRIGHT 110
#define MA_STRING_COMMAND_HELP_HINT_SUBCOMMAND 111
#define MA_STRING_COMMAND_SWITCH_HELP_NAME 112
#define MA_STRING_COMMAND_SWITCH_HELP_DESCRIPTION 113
#define MA_STRING_COMMAND_INVALID_SUBCOMMAND 114
#define MA_STRING_COMMAND_INVALID_OPTION 115
#define MA_STRING_COMMAND_INVALID_ARGUMENT 116
#define MA_STRING_PARAMETER_NAME_DRIVER_PATH 117
#define MA_STRING_MONIKA_COMMAND_NAME   118
#define MA_STRING_MONIKA_COMMAND_DESCRIPTION 119
#define MA_STRING_MONIKA_JUST_MONIKA    120

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
