name: Build

on:
  push:
    branches:
      - "master"
      - "staging"
      - "dev/**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        platform: [x86, x64, ARM, ARM64]
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch everything for build metadata to work
          fetch-depth: 0

      - name: Uninstall Windows SDK/WDK
        run: |
          # Windows SDK/WDK 26100 are problematic. They do not coexist peacefully with older kits.
          # For now, we nuke every existing kit on the cloud and replace them with our own script.
          # Once we migrate to clang for 32-bit and VS2026 for 64-bit, we can remove this step.
          $KitPatterns = @(
            "Windows Software Development Kit - Windows 10.0.*",
            "Windows Driver Kit - Windows 10.0.*"
          )

          $Kits = `
            Get-ChildItem -Path `
              "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall", `
              "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" |
            Get-ItemProperty |
            Where-Object {
                $name = $_.DisplayName
                $match = $false
                foreach ($p in $KitPatterns) { if ($name -like $p) { $match = $true } }
                $match
            }

          foreach ($kit in $Kits) {
            Write-Host "Uninstalling: $($kit.DisplayName)" -ForegroundColor Cyan
            Start-Process cmd.exe -ArgumentList "/c $($kit.QuietUninstallString)" -Wait -NoNewWindow
          }
        shell: powershell

      - name: Install build dependencies
        run: powershell.exe -File ${{ github.workspace }}\setup.ps1
        shell: cmd

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
            msbuild ${{ github.workspace }}\lxmonika.sln ^
                /p:Platform=${{ matrix.platform }} ^
                /p:Configuration=${{ matrix.configuration }}
        shell: cmd

      - name: Pack build artifacts
        run: |
            powershell.exe -File ${{ github.workspace }}\pack.ps1 ^
                -Platform ${{ matrix.platform }} ^
                -Configuration ${{ matrix.configuration }}
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: monika_${{ matrix.configuration }}_${{ matrix.platform }}
          path: out/${{ matrix.configuration }}
